DevTalles/Controllers/CategoriaController.cs
using E_comerce.Data;
using E_comerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace E_comerce.Controllers
{
    [Authorize(Roles = RUTAIMAGEN.admin)]
    public class CategoriaController : Controller
    {
        private readonly ApplicationDbContext _db;


        //por medio de inyeccion de dependencia accedemos al DbContext para manipular los datos
        public CategoriaController(ApplicationDbContext db)
        {
            _db = db;
        }

        //Get Mostramos la lista de Categorias en la vista index
        public async Task<IActionResult> Index()
        {
            var ListaCategoria =await _db.Categorias.ToListAsync();

            return View(ListaCategoria);
        }


        //Get Mostramos el formulario para crear categoria
        public  IActionResult Crear()
        {
            

            return View();
        }

        //Esta Accion Agrega el Registro en la base de datos


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult>Crear(Categoria model)
        {
            if (!ModelState.IsValid) { return NotFound(); }

           await _db.Categorias.AddAsync(model);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");



        }
        //Esta Accion muestra el Registro en la vista
        public IActionResult Editar(int? id)
        {
            if (id is null || id == 0 )
            {
                return NotFound();
            }

            var categoriadb =_db.Categorias.Find(id);
            if (categoriadb is null)
            {
                return NotFound();
            }

            return View(categoriadb);
        }


        //Esta Accion Actualiza el Registro en la base de datos
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult>Editar(Categoria categoria)
        {
            if (!ModelState.IsValid)
            {
                return NotFound();
            }
            _db.Categorias.Update(categoria);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }



        //get Esta Accion muestra la vista eliminar con los datos del modelo a eliminar
        public IActionResult Eliminar(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            var categoriadb = _db.Categorias.Find(id);
            if (categoriadb is null)
            {
                return NotFound();
            }

            return View(categoriadb);
        }
        

        //Esta Accion Elimina el Registro en la base de datos

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Eliminar(Categoria model)
        {
            if (model is null) { return NotFound(); }

            

             _db.Categorias.Remove(model);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");



        }



        [HttpGet]
        public async Task<IActionResult> ValidarNombre(string NombreCategoria)
        {

            var existe = await _db.Categorias.AnyAsync(name => name.NombreCategoria == NombreCategoria);

            if (existe)
            {
                return Json($"El nombre {NombreCategoria} Ya Existe");
            }
            return Json(true);
        }



    }
}

DevTalles/Controllers/ProductoController.cs
using E_comerce.Data;
using E_comerce.Models;
using E_comerce.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace E_comerce.Controllers
{


    [Authorize(Roles =RUTAIMAGEN.admin)]
    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment hostEnvironment;

        public ProductoController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            this.db = db;
            this.hostEnvironment = hostEnvironment;
        }

        //Esta Accion muestra la vista index con una tabla donde se muestran todos los Producto
        public IActionResult Index()
        {

            IEnumerable<Productos> Cursos = db.Producto.Include(c => c.Categoria);
            return View(Cursos);
        }





        //UPSERT Es una Accion que sirve para actualizar campos o agregar campos validando si se pasa el ID

        public async Task<IActionResult> Upsert(int? id)
        {
            var model = new ProductoViewModel()
            {
                producto = new Productos(),
                DropDowmCategoria = DropdownCategoria(),
            };


            if (id == null)
            {
                return View(model);
            }
            else
            {
                model.producto = await db.Producto.FindAsync(id);
                if (model.producto is null)
                {
                    return NotFound();
                }
                return View(model);
            }

        }


        //Esta accion de tipo Post Realiza la correspondiente Actualizacion o Agregacion de datos en la base de datos


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ProductoViewModel model)
        {


            //Validamos que el model sea valido
            if (!ModelState.IsValid)
            {


                model.DropDowmCategoria = DropdownCategoria();

                return View(model);

            }
            else
            {//Comenzamos a ver si se ha cargado algun archivo en la vista

                var file = HttpContext.Request.Form.Files;

                //obtenemos la ruto principal donde se guardara la imagen en este caso la wwwRoot
                var RootPath = hostEnvironment.WebRootPath;

                //si el id de curso es igual a cero significa que crearemos un nuevo curso 
                if (model.producto.Id == 0)
                {



                    //validamos que se guarde una imagen identificando que el usuario desea agregar una imagen

                    if (file.Count > 0)
                    {
                        string Upload = RootPath + RUTAIMAGEN.RutaImagen;
                        string filename = Guid.NewGuid().ToString();
                        var extencion = Path.GetExtension(file[0].FileName);


                        using (FileStream fileStream = new FileStream(Path.Combine(Upload, filename + extencion), FileMode.Create))
                        {
                            file[0].CopyTo(fileStream);
                        }

                        model.producto.ImagenUrl = filename + extencion;
                        db.Producto.Add(model.producto);

                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");

                    }
                    else
                    {
                        //en nuestro sistema requerimos que se seleccione una imagen por lo cual si no se hace regresamos ala misma vista pasandole el model

                        model.DropDowmCategoria = DropdownCategoria();
                        return View(model);

                    }






                }
                else
                {
                    //actualizamo un curso ya existente


                    var cursoDb = await db.Producto.AsNoTracking().FirstOrDefaultAsync(c => c.Id == model.producto.Id);


                    //Actualizamos el curso si agrega una nueva imagen se borra la anterior y se guarda la nueva
                    if (file.Count > 0)
                    {
                        string Upload = RootPath + RUTAIMAGEN.RutaImagen;
                        string filename = Guid.NewGuid().ToString();
                        string extencion = Path.GetExtension(file[0].FileName);

                        var urlimagenAnterior = Path.Combine(Upload, cursoDb.ImagenUrl);



                        if (System.IO.File.Exists(urlimagenAnterior))
                        {
                            System.IO.File.Delete(urlimagenAnterior);
                        }


                        using (FileStream fileStream = new FileStream(Path.Combine(Upload, filename + extencion), FileMode.Create))
                        {
                            file[0].CopyTo(fileStream);
                        }

                        model.producto.ImagenUrl = filename + extencion;
                        db.Producto.Update(model.producto);
                        await db.SaveChangesAsync();

                    }
                    else
                    {
                        //en nuestro sistema requerimos que se seleccione una imagen por lo cual si no se hace regresamos ala misma vista pasandole el model

                        
         
                        
                        model.producto.ImagenUrl = cursoDb.ImagenUrl;
                        db.Producto.Update(model.producto);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }

                }
                return View(model);
            


            }


            

        }

        public IActionResult Eliminar(int id)
        {
            var prod = db.Producto.Find(id);

            if (prod == null)
            {
                return NotFound();
            }
            else
            {


                var RootPath = hostEnvironment.WebRootPath;
                string Upload = RootPath + RUTAIMAGEN.RutaImagen;



                var urlimagenAnterior = Path.Combine(Upload, prod.ImagenUrl);




                if (System.IO.File.Exists(urlimagenAnterior))
                {
                    System.IO.File.Delete(urlimagenAnterior);
                }

                db.Producto.Remove(prod);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
        }



        public IEnumerable<SelectListItem> DropdownCategoria()
        {
            return db.Categorias.Select(c => new SelectListItem(c.NombreCategoria, c.CategoriaId.ToString()));
        }
    }
}

DevTalles/Views/Shared/_Layout.cshtml
@using E_comerce.Data;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] E_comerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>

                        @if(User.IsInRole(RUTAIMAGEN.admin)){

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>

                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                            </li>
                        }


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="color: white">
        <div class="container">
            &copy; 2023 E_comerce
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>